import { useContext } from "react"
import { DesignEditorContext } from "~/contexts/DesignEditor"

const useDesignEditorContext = () => {
  const {
    editorType,
    setEditorType,
    uploadAudio,
    setUploadAudio,
    uploadText,
    setUploadText,
    uploadVoice,
    setUploadVoice,
    uploadFile,
    setUploadFile,
    uploadLive,
    setUploadLive,
    uploadVtuber,
    setUploadVtuber,
    uploadScript,
    setUploadScript,
    uploadLanguage,
    setUploadLanguage,
    uploadVoiceName,
    setUploadVoiceName,
    templateId,
    setTemplateId,
    displayPlayback,
    setDisplayPlayback,
    setDisplayPreview,
    displayPreview,
    currentScene,
    setCurrentScene,
    setScenes,
    scenes,
    maxTime,
    setMaxTime,
    contextMenuTimelineRequest,
    setContextMenuTimelineRequest,
    contextMenuSceneRequest,
    setContextMenuSceneRequest,
    currentDesign,
    setCurrentDesign,
  } = useContext(DesignEditorContext)
  return {
    editorType,
    setEditorType,
    uploadAudio,
    setUploadAudio,
    uploadText,
    setUploadText,
    uploadVoice,
    setUploadVoice,
    uploadFile,
    setUploadFile,
    uploadLive,
    setUploadLive,
    uploadVtuber,
    setUploadVtuber,
    uploadScript,
    setUploadScript,
    uploadLanguage,
    setUploadLanguage,
    uploadVoiceName,
    setUploadVoiceName,
    templateId,
    setTemplateId,
    displayPlayback,
    setDisplayPlayback,
    setDisplayPreview,
    displayPreview,
    currentScene,
    setCurrentScene,
    setScenes,
    scenes,
    maxTime,
    setMaxTime,
    contextMenuTimelineRequest,
    setContextMenuTimelineRequest,
    contextMenuSceneRequest,
    setContextMenuSceneRequest,
    currentDesign,
    setCurrentDesign,
  }
}

export default useDesignEditorContext
